#!/bin/sh
[ -f 'hooks/post-receive.mail' ]    && hooks/post-receive.mail
# [ -f 'hooks/post-receive.bugsweb' ] && hooks/post-receive.bugsweb
[ -f 'hooks/post-receive.mirror' ]  && hooks/post-receive.mirror
